version: '3.8'
services:
  user_management_db:
    image: postgres:15
    container_name: user_management_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: user_management_api
    env_file:
      - .env
    depends_on:
      - user_management_db
    ports:
      - "3000:3000"
    
    command: >
      sh -c "sleep 5 && npx typeorm migration:run -d dist/data-source.js && node dist/main"



volumes:
  pgdata:
